# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default

  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



development:
  <<: *default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  database: paxxa_development
  username: paxxa
  password: paxxa


production:
  <<: *default
  database: paxxa_production
  username: paxxa
  adapter: postgresql
  password: <%= ENV['PAXXA_DATABASE_PASSWORD'] %>
