themes: silver
menubar: true
height: 600
plugins:
  - image
  - link
  - charmap
  - advlist
  - fullscreen
  - code
toolbar:
  - fullscreen | undo redo | styleselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist outdent indent | removeformat | image | link | charmap | code | help
#content_css: 
#  - assets/application.css
